export type CardRank = '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | 'J' | 'Q' | 'K' | 'A'
export type CardSuit = 'Hearts' | 'Diamonds' | 'Clubs' | 'Spades'
export type CardColor = 'red' | 'black'
export type CardBackChoice =
  | 'astronaut'
  | 'abstract_clouds'
  | 'abstract_scene'
  | 'abstract'
  | 'blue'
  | 'blue2'
  | 'cars'
  | 'castle'
  | 'fish'
  | 'frog'
  | 'red'
  | 'red2'
